# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# It's not necessary to copy all keys to your config.
# If the key is missing in your config, "default-config.toml" will serve as a fallback

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
  # 'exec-and-forget /usr/local/bin/borders active_color=0xff7aa2f7 inactive_color=0xff414868 width=15.0',
  'move-workspace-to-monitor --workspace 9 left',
  # 'exec-and-forget /usr/local/bin/sketchybar'

]
# Trigger a custom event in SketchyBar on workspace change
#exec-on-workspace-change = ['/bin/bash', '-c', 'sketchybar --trigger aerospace_workspace_change']

# Optional: Trigger when focus changes within a workspace (to update app icons)
#on-focus-changed = ['/bin/bash', '-c', 'sketchybar --trigger aerospace_workspace_change']
# Notify Sketchybar about workspace change
#exec-on-workspace-change = [
#    '/bin/zsh', 
#    '-c', 
#    '/usr/local/bin/sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
#]

exec-on-workspace-change = [
  '/bin/zsh',
  '-c',
  ' /usr/local/bin/sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]
# Start AeroSpace at login
start-at-login = false

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
#on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
#on-focus-changed = ['move-mouse window-lazy-center'] # Mouse lazily follows any focus (window or workspace)

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 12
inner.vertical = 12
outer.left = 10
outer.bottom = 40
outer.top = 40
outer.right = 10

[workspace-to-monitor-force-assignment]
A = 'secondary'
#2 = 'secondary'
#3 = 'secondary'
#4 = 'secondary'

# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
[mode.main.binding]

alt-enter = 'exec-and-forget /usr/local/bin/borders active_color=0xff7aa2f7 inactive_color=0xff414868 width=15.0'
# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# You can uncomment this line to open up terminal with alt + enter shortcut
# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# alt-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# # See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-h = 'focus left --boundaries-action stop'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-a = 'workspace A'
alt-c = 'workspace C'
alt-d = 'workspace D'
alt-e = 'workspace E'


# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-1 = [
  'move-node-to-workspace 1',
  'exec-and-forget  /usr/local/bin/sketchybar --trigger aerospace_workspace_change',
]
alt-shift-2 = [
  'move-node-to-workspace 2',
  'exec-and-forget  /usr/local/bin/sketchybar --trigger aerospace_workspace_change',
]
alt-shift-3 = [
  'move-node-to-workspace 3',
  'exec-and-forget  /usr/local/bin/sketchybar --trigger aerospace_workspace_change',
]
alt-shift-4 = [
  'move-node-to-workspace 4',
  'exec-and-forget  /usr/local/bin/sketchybar --trigger aerospace_workspace_change',
]
alt-shift-5 = [
  'move-node-to-workspace 5',
  'exec-and-forget  /usr/local/bin/sketchybar --trigger aerospace_workspace_change',
]
alt-shift-6 = [
  'move-node-to-workspace 6',
  'exec-and-forget  /usr/local/bin/sketchybar --trigger aerospace_workspace_change',
]
alt-shift-7 = [
  'move-node-to-workspace 7',
  'exec-and-forget  /usr/local/bin/sketchybar --trigger aerospace_workspace_change',
]
alt-shift-8 = [
  'move-node-to-workspace 8',
  'exec-and-forget  /usr/local/bin/sketchybar --trigger aerospace_workspace_change',
]
alt-shift-9 = [
  'move-node-to-workspace 9',
  'exec-and-forget  /usr/local/bin/sketchybar --trigger aerospace_workspace_change',
]
alt-shift-a = [
  'move-node-to-workspace A',
  'exec-and-forget  /usr/local/bin/sketchybar --trigger aerospace_workspace_change',
]
alt-shift-c = [
  'move-node-to-workspace C',
  'exec-and-forget  /usr/local/bin/sketchybar --trigger aerospace_workspace_change',
]
alt-shift-d = [
  'move-node-to-workspace D',
  'exec-and-forget  /usr/local/bin/sketchybar --trigger aerospace_workspace_change',
]
alt-shift-e = [
  'move-node-to-workspace E',
  'exec-and-forget  /usr/local/bin/sketchybar --trigger aerospace_workspace_change',
]
alt-shift-f = 'fullscreen'
# alt-shift-n = 'move-node-to-workspace N'
alt-n = 'focus-monitor next --wrap-around'
alt-p = "exec-and-forget /Applications/WezTerm.app/Contents/MacOS/wezterm start -- zsh -ci 'source ~/.zshrc && asw'"
# next non empty workspace
alt-m = "exec-and-forget  /usr/local/bin/aerospace list-workspaces --monitor focused --empty no | /usr/local/bin/aerospace workspace --stdin next"
shift-alt-m = "exec-and-forget  /usr/local/bin/aerospace list-workspaces --monitor focused --empty no | /usr/local/bin/aerospace workspace --stdin prev"


alt-b = '''exec-and-forget osascript -e '
tell application "Safari"
    make new document at end of documents
    activate
end tell'
'''

alt-t = 'exec-and-forget open -n -a /Applications/WezTerm.app'

alt-r = 'exec-and-forget open -n -a skim'


# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth' # I should change this shortcut to focus monitor
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = [
  'move-workspace-to-monitor --wrap-around next',
  'exec-and-forget  /usr/local/bin/sketchybar --trigger aerospace_workspace_change',
]

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-shift-semicolon = 'mode service'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
f = [
  'layout floating tiling',
  'mode main',
] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

1 = [
  'move-workspace-to-monitor --workspace 1 right',
  'move-workspace-to-monitor --workspace A left',
  'workspace 1',
  'workspace A',
  'focus-monitor right',
  'mode main',
]
2 = ['workspace 2', 'workspace B', 'focus-monitor right', 'mode main']
3 = ['workspace 3', 'workspace C', 'focus-monitor right', 'mode main']
4 = ['workspace 4', 'workspace D', 'focus-monitor right', 'mode main']

# Move to Workspace A - Code editors and development tools.

[[on-window-detected]]
if.window-title-regex-substring = 'asw'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = ['move-node-to-workspace A']

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
check-further-callbacks = true
run = ['move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = 'dev.warp.Warp-Stable'
run = ['move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = 'org.videolan.vlc'
run = ['layout tiling', 'move-node-to-workspace 4']

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
if.window-title-regex-substring = 'SNOW'
run = [
  'move-workspace-to-monitor --workspace 2 left',
  'move-node-to-workspace 2',
]
[[on-window-detected]]
if.app-id = 'com.apple.Safari'
if.window-title-regex-substring = 'Personal'
run = [
  'move-workspace-to-monitor --workspace 3 left',
  'move-node-to-workspace 3',
]

[[on-window-detected]]
if.app-id = 'net.sourceforge.skim-app.skim'
run = ['move-node-to-workspace 6', 'move-workspace-to-monitor left']


[[on-window-detected]]
if.app-id = 'com.apple.journal'
run = ['layout floating']
